app = "telegram-udt-vip-join-bot"

[build]
  buildpacks = ["heroku/buildpack-python"]

[env]

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
